apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - etcd-service.yaml
  - etcd-statefulset.yaml

configMapGenerator:
  - name: arca-dns-controller-config
    behavior: replace
    files:
      - controller.yaml=controller.yaml

generatorOptions:
  disableNameSuffixHash: true

