package parser

import (
	"fmt"
	"net"
	"strings"

	"github.com/akam1o/arca-dns/pkg/model"
	"github.com/miekg/dns"
)

// GenerateBINDZoneFile converts a Zone model to BIND format zone file.
// The output is compatible with named-checkzone validation.
func GenerateBINDZoneFile(zone *model.Zone) (string, error) {
	if zone == nil {
		return "", fmt.Errorf("zone is nil")
	}

	var buf strings.Builder

	// Write zone header comment
	buf.WriteString(fmt.Sprintf("; Zone: %s\n", zone.Name))
	buf.WriteString(fmt.Sprintf("; Generated by arca-dns\n"))
	buf.WriteString(fmt.Sprintf("; Version: %s\n", zone.Version))
	buf.WriteString("\n")

	// Write $ORIGIN directive
	buf.WriteString(fmt.Sprintf("$ORIGIN %s\n", zone.Name))
	buf.WriteString("\n")

	// Write SOA record
	soa := dns.SOA{
		Hdr: dns.RR_Header{
			Name:   zone.Name,
			Rrtype: dns.TypeSOA,
			Class:  dns.ClassINET,
			Ttl:    zone.SOA.Minimum, // SOA TTL typically uses the minimum value
		},
		Ns:      zone.SOA.MName,
		Mbox:    zone.SOA.RName,
		Serial:  zone.SOA.Serial,
		Refresh: zone.SOA.Refresh,
		Retry:   zone.SOA.Retry,
		Expire:  zone.SOA.Expire,
		Minttl:  zone.SOA.Minimum,
	}
	buf.WriteString(soa.String())
	buf.WriteString("\n")

	// Write records
	for _, record := range zone.Records {
		rr, err := convertRecordToRR(zone.Name, &record)
		if err != nil {
			return "", fmt.Errorf("failed to convert record %s: %w", record.Name, err)
		}
		buf.WriteString(rr.String())
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

// GenerateBINDZoneFileFromRRs generates a BIND zone file from dns.RR records.
// This is used for DNSSEC-signed zones which include DNSKEY, RRSIG, NSEC3, and NSEC3PARAM records.
func GenerateBINDZoneFileFromRRs(zoneName, version string, rrs []dns.RR) (string, error) {
	if len(rrs) == 0 {
		return "", fmt.Errorf("no RRs provided")
	}

	var buf strings.Builder

	// Write zone header comment
	buf.WriteString(fmt.Sprintf("; Zone: %s\n", zoneName))
	buf.WriteString(fmt.Sprintf("; Generated by arca-dns (DNSSEC-signed)\n"))
	buf.WriteString(fmt.Sprintf("; Version: %s\n", version))
	buf.WriteString("\n")

	// Write $ORIGIN directive
	buf.WriteString(fmt.Sprintf("$ORIGIN %s\n", zoneName))
	buf.WriteString("\n")

	// Write all RRs in order
	for _, rr := range rrs {
		buf.WriteString(rr.String())
		buf.WriteString("\n")
	}

	return buf.String(), nil
}

// convertRecordToRR converts a model.Record to dns.RR (Resource Record).
func convertRecordToRR(origin string, record *model.Record) (dns.RR, error) {
	// Convert relative name to FQDN
	name := record.Name
	if name == "@" {
		name = origin
	} else if !strings.HasSuffix(name, ".") {
		name = name + "." + origin
	}

	// Create RR header
	hdr := dns.RR_Header{
		Name:   name,
		Class:  dns.ClassINET,
		Ttl:    record.TTL,
	}

	// Create specific RR type
	switch record.Type {
	case model.RecordTypeA:
		hdr.Rrtype = dns.TypeA
		return &dns.A{
			Hdr: hdr,
			A:   net.ParseIP(record.Value).To4(),
		}, nil

	case model.RecordTypeAAAA:
		hdr.Rrtype = dns.TypeAAAA
		return &dns.AAAA{
			Hdr:  hdr,
			AAAA: net.ParseIP(record.Value),
		}, nil

	case model.RecordTypeCNAME:
		hdr.Rrtype = dns.TypeCNAME
		target := record.Value
		if !strings.HasSuffix(target, ".") {
			target = target + "."
		}
		return &dns.CNAME{
			Hdr:    hdr,
			Target: target,
		}, nil

	case model.RecordTypeNS:
		hdr.Rrtype = dns.TypeNS
		ns := record.Value
		if !strings.HasSuffix(ns, ".") {
			ns = ns + "."
		}
		return &dns.NS{
			Hdr: hdr,
			Ns:  ns,
		}, nil

	case model.RecordTypeMX:
		hdr.Rrtype = dns.TypeMX
		// Parse MX value "priority target"
		parts := strings.Fields(record.Value)
		if len(parts) != 2 {
			return nil, fmt.Errorf("invalid MX value format: %s", record.Value)
		}
		var priority uint16
		_, err := fmt.Sscanf(parts[0], "%d", &priority)
		if err != nil {
			return nil, fmt.Errorf("invalid MX priority: %s", parts[0])
		}
		mx := parts[1]
		if !strings.HasSuffix(mx, ".") {
			mx = mx + "."
		}
		return &dns.MX{
			Hdr:        hdr,
			Preference: priority,
			Mx:         mx,
		}, nil

	case model.RecordTypeTXT:
		hdr.Rrtype = dns.TypeTXT
		return &dns.TXT{
			Hdr: hdr,
			Txt: []string{record.Value},
		}, nil

	case model.RecordTypePTR:
		hdr.Rrtype = dns.TypePTR
		ptr := record.Value
		if !strings.HasSuffix(ptr, ".") {
			ptr = ptr + "."
		}
		return &dns.PTR{
			Hdr: hdr,
			Ptr: ptr,
		}, nil

	case model.RecordTypeSRV:
		hdr.Rrtype = dns.TypeSRV
		// Parse SRV value "priority weight port target"
		parts := strings.Fields(record.Value)
		if len(parts) != 4 {
			return nil, fmt.Errorf("invalid SRV value format: %s", record.Value)
		}
		var priority, weight, port uint16
		_, err := fmt.Sscanf(parts[0], "%d", &priority)
		if err != nil {
			return nil, fmt.Errorf("invalid SRV priority: %s", parts[0])
		}
		_, err = fmt.Sscanf(parts[1], "%d", &weight)
		if err != nil {
			return nil, fmt.Errorf("invalid SRV weight: %s", parts[1])
		}
		_, err = fmt.Sscanf(parts[2], "%d", &port)
		if err != nil {
			return nil, fmt.Errorf("invalid SRV port: %s", parts[2])
		}
		target := parts[3]
		if !strings.HasSuffix(target, ".") {
			target = target + "."
		}
		return &dns.SRV{
			Hdr:      hdr,
			Priority: priority,
			Weight:   weight,
			Port:     port,
			Target:   target,
		}, nil

	case model.RecordTypeCAA:
		hdr.Rrtype = dns.TypeCAA
		// Parse CAA value "flags tag value"
		parts := strings.Fields(record.Value)
		if len(parts) < 3 {
			return nil, fmt.Errorf("invalid CAA value format: %s", record.Value)
		}
		var flags uint8
		_, err := fmt.Sscanf(parts[0], "%d", &flags)
		if err != nil {
			return nil, fmt.Errorf("invalid CAA flags: %s", parts[0])
		}
		tag := parts[1]
		value := strings.Join(parts[2:], " ")
		// Remove quotes if present
		value = strings.Trim(value, "\"")
		return &dns.CAA{
			Hdr:   hdr,
			Flag:  flags,
			Tag:   tag,
			Value: value,
		}, nil

	default:
		return nil, fmt.Errorf("unsupported record type: %s", record.Type)
	}
}
