apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - controller-configmap.yaml
  - controller-secret.yaml
  - controller-deployment.yaml
  - controller-service.yaml
  - etcd-service.yaml
  - etcd-statefulset.yaml
