apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: arca-dns-controller
  annotations:
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/limit-req-status-code: "429"
spec:
  ingressClassName: nginx
  rules:
    - host: controller.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: arca-dns-controller
                port:
                  number: 8080
