package bird

import (
	"fmt"
	"net"
	"net/netip"
	"regexp"
	"sort"
	"strings"

	"github.com/akam1o/arca-dns/pkg/config"
)

var birdIdentifierRE = regexp.MustCompile(`^[A-Za-z_][A-Za-z0-9_]*$`)

// RenderAnycastConfig renders a BIRD configuration snippet for advertising anycast prefixes
// to one or more upstream neighbors. The caller is responsible for writing it to disk and
// ensuring the main bird.conf includes it.
//
// It returns (configText, protocolNames, error).
func RenderAnycastConfig(cfg config.BIRDConfig) (string, []string, error) {
	if !cfg.ConfigureOnStart.Enabled {
		return "", nil, fmt.Errorf("config generation disabled")
	}

	gen := cfg.ConfigureOnStart

	if net.ParseIP(gen.RouterID) == nil {
		return "", nil, fmt.Errorf("invalid bird.config.router_id: %q", gen.RouterID)
	}
	if net.ParseIP(gen.SourceIP) == nil {
		return "", nil, fmt.Errorf("invalid bird.config.source_ip: %q", gen.SourceIP)
	}

	v4Prefixes, v6Prefixes, err := classifyAnycastPrefixes(cfg.AnycastPrefixes)
	if err != nil {
		return "", nil, err
	}
	sort.Strings(v4Prefixes)
	sort.Strings(v6Prefixes)

	// Prefer explicit protocols config.
	var protocolNames []string
	type neighbor struct {
		address string
		asn     uint32
	}
	var neighbors []neighbor

	if len(cfg.Protocols) > 0 {
		protocolNames = make([]string, 0, len(cfg.Protocols))
		neighbors = make([]neighbor, 0, len(cfg.Protocols))
		for _, p := range cfg.Protocols {
			if err := validateBIRDIdentifier("bird.protocols.name", p.Name); err != nil {
				return "", nil, err
			}
			protocolNames = append(protocolNames, p.Name)
			neighbors = append(neighbors, neighbor{address: p.NeighborAddress, asn: p.NeighborASN})
		}
	} else {
		// Legacy: neighbors + protocol_names/protocol_name.
		protocolNames = cfg.ProtocolNames
		baseName := cfg.ProtocolName
		if baseName == "" {
			baseName = "anycast"
		}
		if len(protocolNames) == 0 {
			if err := validateBIRDIdentifier("bird.protocol_name", baseName); err != nil {
				return "", nil, err
			}
			protocolNames = make([]string, 0, len(gen.Neighbors))
			for i := range gen.Neighbors {
				protocolNames = append(protocolNames, fmt.Sprintf("%s_%d", baseName, i+1))
			}
		}
		for _, n := range gen.Neighbors {
			neighbors = append(neighbors, neighbor{address: n.Address, asn: n.ASN})
		}
	}

	if err := validateBIRDIdentifiers("bird.protocol_names", protocolNames); err != nil {
		return "", nil, err
	}

	b := &strings.Builder{}
	fmt.Fprintln(b, "# Generated by arca-dns-agent (BIRD anycast snippet). DO NOT EDIT.")
	fmt.Fprintf(b, "router id %s;\n\n", gen.RouterID)

	if gen.BFD.Enabled {
		minRx := gen.BFD.MinRx
		minTx := gen.BFD.MinTx
		mult := gen.BFD.Multiplier
		if mult == 0 {
			mult = 5
		}
		fmt.Fprintln(b, "protocol bfd {")
		fmt.Fprintln(b, `  interface "*";`)
		if minRx > 0 {
			fmt.Fprintf(b, "  min rx interval %s;\n", minRx)
		}
		if minTx > 0 {
			fmt.Fprintf(b, "  min tx interval %s;\n", minTx)
		}
		fmt.Fprintf(b, "  multiplier %d;\n", mult)
		fmt.Fprintln(b, "}")
		fmt.Fprintln(b)
	}

	fmt.Fprintln(b, "filter arca_dns_anycast_export_v4 {")
	if len(v4Prefixes) > 0 {
		fmt.Fprintf(b, "  if net ~ [ %s ] then accept;\n", strings.Join(v4Prefixes, ", "))
	}
	fmt.Fprintln(b, "  reject;")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)

	fmt.Fprintln(b, "filter arca_dns_anycast_export_v6 {")
	if len(v6Prefixes) > 0 {
		fmt.Fprintf(b, "  if net ~ [ %s ] then accept;\n", strings.Join(v6Prefixes, ", "))
	}
	fmt.Fprintln(b, "  reject;")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)

	fmt.Fprintln(b, "protocol static arca_dns_anycast {")
	if len(v4Prefixes) > 0 {
		fmt.Fprintln(b, "  ipv4;")
		for _, p := range v4Prefixes {
			fmt.Fprintf(b, "  route %s blackhole;\n", p)
		}
	}
	if len(v6Prefixes) > 0 {
		fmt.Fprintln(b, "  ipv6;")
		for _, p := range v6Prefixes {
			fmt.Fprintf(b, "  route %s blackhole;\n", p)
		}
	}
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)

	fmt.Fprintln(b, "template bgp arca_dns_anycast_template {")
	fmt.Fprintf(b, "  local as %d;\n", gen.LocalAS)
	fmt.Fprintf(b, "  source address %s;\n", gen.SourceIP)
	if gen.BFD.Enabled {
		fmt.Fprintln(b, "  bfd on;")
	}
	fmt.Fprintln(b, "  ipv4 { import none; export filter arca_dns_anycast_export_v4; };")
	fmt.Fprintln(b, "  ipv6 { import none; export filter arca_dns_anycast_export_v6; };")
	fmt.Fprintln(b, "}")
	fmt.Fprintln(b)

	if len(neighbors) != len(protocolNames) {
		return "", nil, fmt.Errorf("bird protocol count (%d) must match neighbor count (%d)", len(protocolNames), len(neighbors))
	}

	for i, n := range neighbors {
		if net.ParseIP(n.address) == nil {
			return "", nil, fmt.Errorf("invalid neighbor address: %q", n.address)
		}
		if n.asn == 0 {
			return "", nil, fmt.Errorf("invalid neighbor ASN for %q: must be > 0", n.address)
		}
		fmt.Fprintf(b, "protocol bgp %s from arca_dns_anycast_template {\n", protocolNames[i])
		fmt.Fprintf(b, "  neighbor %s as %d;\n", n.address, n.asn)
		fmt.Fprintln(b, "}")
		fmt.Fprintln(b)
	}

	return b.String(), protocolNames, nil
}

func classifyAnycastPrefixes(prefixes []string) ([]string, []string, error) {
	var v4Prefixes []string
	var v6Prefixes []string

	for _, raw := range prefixes {
		p := strings.TrimSpace(raw)
		if p == "" {
			continue
		}

		parsed, err := netip.ParsePrefix(p)
		if err != nil {
			return nil, nil, fmt.Errorf("invalid bird.anycast_prefixes entry %q: %w", p, err)
		}

		if parsed.Addr().Is4() {
			v4Prefixes = append(v4Prefixes, p)
			continue
		}
		if parsed.Addr().Is6() {
			v6Prefixes = append(v6Prefixes, p)
			continue
		}
		return nil, nil, fmt.Errorf("invalid bird.anycast_prefixes entry %q: unsupported IP family", p)
	}

	return v4Prefixes, v6Prefixes, nil
}

func validateBIRDIdentifiers(field string, names []string) error {
	for _, name := range names {
		if err := validateBIRDIdentifier(field, name); err != nil {
			return err
		}
	}
	return nil
}

func validateBIRDIdentifier(field, name string) error {
	if !birdIdentifierRE.MatchString(name) {
		return fmt.Errorf("invalid %s: %q must match %s", field, name, birdIdentifierRE.String())
	}
	return nil
}
