# Type Path                     Mode UID  GID  Age Argument
d /etc/arca-dns                0750 root root -   -
d /var/lib/arca-dns            0750 root root -   -
d /var/lib/arca-dns/keys       0750 root root -   -
d /var/lib/arca-dns/artifacts  0750 root root -   -
d /var/log/arca-dns            0750 root root -   -

