package unbound

import (
	"bytes"
	"context"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"text/template"
	"time"

	"github.com/akam1o/arca-dns/pkg/config"
	"github.com/akam1o/arca-dns/pkg/model"
	"github.com/akam1o/arca-dns/pkg/util"
	"go.uber.org/zap"
)

// Controller manages Unbound operations via unbound-control.
type Controller struct {
	config config.UnboundConfig
	logger *zap.Logger
}

// NewController creates a new Unbound controller.
func NewController(cfg config.UnboundConfig, logger *zap.Logger) *Controller {
	return &Controller{
		config: cfg,
		logger: logger,
	}
}

// Reload reloads Unbound configuration.
func (c *Controller) Reload() error {
	if !c.config.Enabled {
		c.logger.Debug("Unbound is disabled, skipping reload")
		return nil
	}

	c.logger.Info("Reloading Unbound configuration")

	ctx, cancel := context.WithTimeout(context.Background(), c.config.ReloadTimeout)
	defer cancel()

	cmd := exec.CommandContext(ctx, c.config.ControlPath, "reload")

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("unbound-control reload failed: %w, stderr: %s", err, stderr.String())
	}

	c.logger.Info("Unbound configuration reloaded successfully",
		zap.String("output", stdout.String()))

	return nil
}

// CheckConfig validates Unbound configuration file.
func (c *Controller) CheckConfig() error {
	if !c.config.Enabled {
		c.logger.Debug("Unbound is disabled, skipping config check")
		return nil
	}

	c.logger.Debug("Validating Unbound configuration",
		zap.String("config", c.config.ConfigPath))

	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()

	// Pass the config file path to unbound-checkconf
	cmd := exec.CommandContext(ctx, c.config.CheckconfPath, c.config.ConfigPath)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("unbound config validation failed: %w, output: %s, stderr: %s",
			err, stdout.String(), stderr.String())
	}

	c.logger.Debug("Unbound configuration is valid",
		zap.String("output", stdout.String()))

	return nil
}

// Status retrieves Unbound status.
func (c *Controller) Status() (string, error) {
	if !c.config.Enabled {
		return "disabled", nil
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, c.config.ControlPath, "status")

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return "", fmt.Errorf("unbound-control status failed: %w, stderr: %s", err, stderr.String())
	}

	return strings.TrimSpace(stdout.String()), nil
}

// IsRunning checks if Unbound is running and responsive.
func (c *Controller) IsRunning() bool {
	if !c.config.Enabled {
		return false
	}

	ctx, cancel := context.WithTimeout(context.Background(), 2*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, c.config.ControlPath, "status")

	if err := cmd.Run(); err != nil {
		c.logger.Debug("Unbound is not running or not responsive",
			zap.Error(err))
		return false
	}

	return true
}

// GenerateStubZoneConfig generates Unbound stub-zone configuration for a zone.
// This configuration points Unbound to the local NSD instance for the given zone.
func (c *Controller) GenerateStubZoneConfig(zoneName string) (string, error) {
	normalized, err := normalizeZoneName(zoneName)
	if err != nil {
		return "", err
	}

	tmpl := `# Stub zone for {{ .ZoneName }}
# Generated by arca-dns-agent
stub-zone:
    name: "{{ .ZoneName }}"
    stub-addr: {{ .NSDAddress }}@{{ .NSDPort }}
`

	t, err := template.New("stubzone").Parse(tmpl)
	if err != nil {
		return "", fmt.Errorf("failed to parse template: %w", err)
	}

	var buf bytes.Buffer
	data := struct {
		ZoneName   string
		NSDAddress string
		NSDPort    int
	}{
		ZoneName:   normalized,
		NSDAddress: c.config.StubZoneConfig.NSDAddress,
		NSDPort:    c.config.StubZoneConfig.NSDPort,
	}

	if err := t.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("failed to execute template: %w", err)
	}

	return buf.String(), nil
}

// UpdateStubZoneConfig updates the stub-zone configuration file for a zone.
// This creates or updates a zone-specific config file that Unbound can include.
func (c *Controller) UpdateStubZoneConfig(zoneName string) error {
	if !c.config.Enabled {
		c.logger.Debug("Unbound is disabled, skipping stub-zone update")
		return nil
	}

	c.logger.Info("Updating stub-zone configuration",
		zap.String("zone", zoneName))

	normalized, err := normalizeZoneName(zoneName)
	if err != nil {
		return err
	}

	// Generate stub-zone config
	stubConfig, err := c.GenerateStubZoneConfig(normalized)
	if err != nil {
		return fmt.Errorf("failed to generate stub-zone config: %w", err)
	}

	stubZoneFile := c.stubZoneConfigPath(normalized)

	if err := os.WriteFile(stubZoneFile, []byte(stubConfig), 0644); err != nil {
		return fmt.Errorf("failed to write stub-zone config: %w", err)
	}

	c.logger.Info("Stub-zone configuration updated",
		zap.String("zone", normalized),
		zap.String("file", stubZoneFile))

	return nil
}

// DeleteStubZoneConfig removes the generated stub-zone configuration file for a zone.
func (c *Controller) DeleteStubZoneConfig(zoneName string) error {
	if !c.config.Enabled {
		c.logger.Debug("Unbound is disabled, skipping stub-zone deletion")
		return nil
	}

	normalized, err := normalizeZoneName(zoneName)
	if err != nil {
		return err
	}

	stubZoneFile := c.stubZoneConfigPath(normalized)
	if err := os.Remove(stubZoneFile); err != nil {
		if os.IsNotExist(err) {
			c.logger.Debug("Stub-zone configuration already absent",
				zap.String("zone", normalized),
				zap.String("file", stubZoneFile))
			return nil
		}
		return fmt.Errorf("failed to delete stub-zone config: %w", err)
	}

	c.logger.Info("Stub-zone configuration deleted",
		zap.String("zone", normalized),
		zap.String("file", stubZoneFile))

	return nil
}

func (c *Controller) stubZoneConfigPath(zoneName string) string {
	configDir := filepath.Dir(c.config.ConfigPath)
	safeName := util.SafeZoneFilename(zoneName)
	return filepath.Join(configDir, fmt.Sprintf("stub-zone-%s.conf", safeName))
}

// EnsureEDNSBufferSize checks and logs a warning if EDNS buffer size is not set to 1232.
// This is critical for ECMP safety as specified in SPEC.md.
// Note: This is a check-only function; actual configuration must be done in unbound.conf.
func (c *Controller) EnsureEDNSBufferSize() error {
	if !c.config.Enabled {
		return nil
	}

	expectedSize := 1232 // ECMP-safe value from SPEC.md

	if c.config.EDNSBufferSize != expectedSize {
		c.logger.Warn("EDNS buffer size is not set to ECMP-safe value",
			zap.Int("current", c.config.EDNSBufferSize),
			zap.Int("expected", expectedSize),
			zap.String("note", "Update unbound.conf with: edns-buffer-size: 1232"))
		return fmt.Errorf("EDNS buffer size mismatch: expected %d, got %d", expectedSize, c.config.EDNSBufferSize)
	}

	c.logger.Info("EDNS buffer size is correctly configured",
		zap.Int("size", c.config.EDNSBufferSize))

	return nil
}

// FlushZone flushes a specific zone from Unbound's cache.
func (c *Controller) FlushZone(zoneName string) error {
	if !c.config.Enabled {
		c.logger.Debug("Unbound is disabled, skipping zone flush")
		return nil
	}

	c.logger.Info("Flushing zone from Unbound cache",
		zap.String("zone", zoneName))

	normalized, err := normalizeZoneName(zoneName)
	if err != nil {
		return err
	}

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	cmd := exec.CommandContext(ctx, c.config.ControlPath, "flush_zone", normalized)

	var stdout, stderr bytes.Buffer
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("unbound-control flush_zone failed: %w, stderr: %s", err, stderr.String())
	}

	c.logger.Info("Zone flushed successfully from Unbound cache",
		zap.String("zone", normalized),
		zap.String("output", stdout.String()))

	return nil
}

func normalizeZoneName(zoneName string) (string, error) {
	normalized := model.NormalizeZoneName(zoneName)
	if err := model.ValidateZoneName(normalized); err != nil {
		return "", fmt.Errorf("invalid zone name %q: %w", zoneName, err)
	}
	return normalized, nil
}
