name: build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GOCACHE: ${{ github.workspace }}/.cache/go-build
      GOPATH: ${{ github.workspace }}/.cache/gopath
      GOMODCACHE: ${{ github.workspace }}/.cache/gomod
    steps:
      - uses: actions/checkout@v4

      - id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Cache go
        uses: actions/cache@v4
        with:
          path: |
            .cache/go-build
            .cache/gomod
            .cache/gopath
          key: ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-${{ hashFiles('**/go.sum') }}-build
          restore-keys: |
            ${{ runner.os }}-go-${{ steps.setup-go.outputs.go-version }}-
            ${{ runner.os }}-go-

      - name: Build
        run: |
          mkdir -p "$GOCACHE"
          make build
