name: lint

on:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      GOCACHE: ${{ github.workspace }}/.cache/go-build
      GOPATH: ${{ github.workspace }}/.cache/gopath
      GOMODCACHE: ${{ github.workspace }}/.cache/gomod
      GOLANGCI_LINT_CACHE: ${{ github.workspace }}/.cache/golangci-lint
    steps:
      - uses: actions/checkout@v4

      - id: setup-go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum

      - name: golangci-lint
        run: |
          mkdir -p "$GOCACHE"
          make install-tools lint
